### ISSUE TITLE
Storybook - Image page

### ISSUE THREAD

**Issue by 0xfr4nkie** [ASU-CodeDevils/CD-Library#14]
Arguments in the `Image.stories.tsx` generates the following error message:
```
Type '""' is not assignable to type '"bottom aligend" | "middle aligned" | "top aligned" | undefined'.
```

Arguments for undefined is either typing directly `undefined` or simply not assigning the undefined arguments.

**Comment by KohNagae** [comment]
I removed aligned, spaced, and floated props from Primary.args and made a new PR.
