### ISSUE TITLE
Add start and end icons to Button component

### ISSUE THREAD

**Issue by KevinThePepper** [ASU-CodeDevils/CD-Library#25]
Add 2 props to the `Button` component called `startIcon` and `endIcon` that adds an icon to the corresponding side of the `Button` component text.

[Example - Material UI](https://mui.com/material-ui/react-button/#buttons-with-icons-and-label)

**Comment by Aminehassou** [comment]
Hey, I'd like to work on this. Could you clarify on where I should make a pull request. Is the starting point the staging branch?
